// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDq2xZZg7EZHjus64YMUbME1rl2vqI8-hk',
    appId: '1:203845496649:web:a5dff8e8789ea7e234b498',
    messagingSenderId: '203845496649',
    projectId: 'smart-system-f4f24',
    authDomain: 'smart-system-f4f24.firebaseapp.com',
    storageBucket: 'smart-system-f4f24.firebasestorage.app',
    measurementId: 'G-PV8DL68JE0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPg3lGzKI4SVaIoAdxNCbK3PJfPp-LSq4',
    appId: '1:203845496649:android:e8c44baca7c7705534b498',
    messagingSenderId: '203845496649',
    projectId: 'smart-system-f4f24',
    storageBucket: 'smart-system-f4f24.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmoRh72LhUc4M75wgtiJHKcxuw9nVkFEg',
    appId: '1:203845496649:ios:7dbce6cbb808ee4734b498',
    messagingSenderId: '203845496649',
    projectId: 'smart-system-f4f24',
    storageBucket: 'smart-system-f4f24.firebasestorage.app',
    iosBundleId: 'com.example.smartCrimeReporting',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmoRh72LhUc4M75wgtiJHKcxuw9nVkFEg',
    appId: '1:203845496649:ios:7dbce6cbb808ee4734b498',
    messagingSenderId: '203845496649',
    projectId: 'smart-system-f4f24',
    storageBucket: 'smart-system-f4f24.firebasestorage.app',
    iosBundleId: 'com.example.smartCrimeReporting',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDq2xZZg7EZHjus64YMUbME1rl2vqI8-hk',
    appId: '1:203845496649:web:193dad84f4081efa34b498',
    messagingSenderId: '203845496649',
    projectId: 'smart-system-f4f24',
    authDomain: 'smart-system-f4f24.firebaseapp.com',
    storageBucket: 'smart-system-f4f24.firebasestorage.app',
    measurementId: 'G-JK8CQHLGJR',
  );
}
